version: '3'

services:
  mydb:
    image: mariadb:latest 
    networks:
      - my-bridge
    volumes: 
      - db_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vvp
      MYSQL_PASSWORD: vvp
      MYSQL_DATABASE: vvp_db
      
  wp:
    image: wordpress:latest
    networks:
      - my-bridge
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mydb
      WORDPRESS_DB_USER: vvp
      WORDPRESS_DB_PASSWORD: vvp
      WORDPRESS_DB_NAME: vvp_db
    volumes:
      - wp_storage:/var/www/html
            
networks:
  my-bridge:
    driver: bridge

volumes:
   db_storage:
   wp_storage:
